### ISSUE TITLE
Incorrect configuration line - wrong regexp

### ISSUE THREAD

**Issue by dracorp** [karlot/sshclick#4]
Hi
For ssht:
```
$ ssht
WARNING:root:KEYWORD: Incorrect configuration line 'HostKeyAlgorithms=+ssh-dss,ssh-rsa' on SSH-config line number 241
WARNING:root:KEYWORD: Incorrect configuration line 'PubkeyAcceptedKeyTypes=+ssh-dss,ssh-rsa' on SSH-config line number 242
WARNING:root:KEYWORD: Incorrect configuration line 'HostKeyAlgorithms=+ssh-dss,ssh-rsa' on SSH-config line number 246
WARNING:root:KEYWORD: Incorrect configuration line 'PubkeyAcceptedKeyTypes=+ssh-dss,ssh-rsa' on SSH-config line number 247
```
because of ssh_config.py:132
```
match = re.search(r"^(\w+)\s+(.+)$", line)
```

In addition, the line number is wrong:
```
  1 #------------------------
241 Host gdndev112 gdndev112.
  1     HostKeyAlgorithms=+ss
  2     PubkeyAcceptedKeyType
  3
```

**Comment by dracorp** [comment]
Probably both are wrong:

> Configuration options may be separated by whitespace or optional whitespace and exactly one ‘=’; the latter format is useful to avoid the need to quote  whitespace when specifying configuration options using the ssh, scp, and sftp -o option

**Comment by karlot** [comment]
You are right, currently regex is working for reading config parameters assuming only whitespace separation, I'll have to update regex to cover also optional "=" separator when "reading" the ssh config file.

However when ssh config file is changed or re-rendered due to adding or changing parameters, only one "style" should be preferred. That could be handled trough embedded meta config I guess, or some ENV var. 
I would avoid supporting mixes of both types when reading and re-writing the same config file, at the end, that was the point of the tool for me, to be consistent in specific style and keeping the config "clean"-ish. :)


But from your Host definition I can see I have totally overlooked option to define multiple hostname definitions on the same line!
> The Host directive can contain one pattern or a whitespace-separated list of patterns. 

For instance:
```
Host test test.tmp
    ...
```

In this case parsing the host `name` internally will try to use it as `test text.lab`... This looks like it would not cause big issue, and even rendering configuration back will work, however... for sure its not correct! :)
And then using some TUI feature, connect options will not work as they take the `name` part and pass it to local `ssh` or `sftp` shell commands via subprocess fork.
In this case that would not work as expected, as it would result in `ssh test test.tmp` execution, which would establish connection to `test` host, but then try to execute `test.tmp` command. :)


As I have some new changes that I haven't pushed in a while, I'll try to merge some of this fixes as well.

**Comment by karlot** [comment]
Unfortunately I had to update all unmerged changes, and not in very clean way... :/
Anyway main branch is now up to date.... but not really ready for release to PyPI.

In main branch, I've added support for multiple entry names in config file, and parsing of config file with optional "=" symbol between keyword and attributes, with tests that cover that. Alt names are visible in the object and renderable in all currently supported styles in outputs (and will persist config changes trough sshc commands).

If you want to test current release from main branch, you can install it from source.
(its alpha... so it has some new stuff coming to TUI part, but only visual, not functional yet)

!! Please note that although parsing can now properly read parameters with "=", if configuration is edited, output rendering will default to using just space as separator. So if you prefer to have "=" in your config files, use only show and list commands. :)
Otherwise your config will be re-rendered with spaces as defaults.

I plan to add this as other "global config" option, that can be changed on the fly, and it will affect and re-render whole config with one of the preferred styles.

**Comment by dracorp** [comment]
Now is worse:
```
$ ssht
WARNING:root:META: Unhandled metadata 'CanonicalizeFallbackLocal' on SSH-config line number: 18
WARNING:root:META: Unhandled metadata 'Disable' on SSH-config line number: 21
WARNING:root:META: Unhandled metadata 'VerifyHostKeyDNS' on SSH-config line number: 23
WARNING:root:META: Unhandled metadata 'CheckHostIP' on SSH-config line number: 24
WARNING:root:META: Unhandled metadata 'https' on SSH-config line number: 26
WARNING:root:META: Unhandled metadata 'HashKnownHosts' on SSH-config line number: 27
WARNING:root:META: Unhandled metadata 'UpdateHostKeys' on SSH-config line number: 28
```
